"""
Theremin GUI v1.0
テルミン設定GUI + 実行ランチャー
クロスプラットフォーム (Windows / macOS / Linux + Python)
"""

import tkinter as tk
from tkinter import ttk, messagebox, scrolledtext
import subprocess
import sys
import os
import threading
import json
import math

# ──────────────────────────────────────────────
# デフォルト設定値
# ──────────────────────────────────────────────
DEFAULTS = {
    # スケール
    "scale_name": "B Minor Pentatonic",
    "custom_pcs": "4, 11, 1",
    # 音域
    "f_min": 110.0,
    "octaves": 3.0,
    "y_low": 0.85,
    "y_high": 0.15,
    # オーディオ
    "device_index": 8,
    "samplerate": 48000,
    "blocksize": 256,
    # ピンチ感度
    "pinch_min": 0.02,
    "pinch_max": 0.20,
    "amp_min": 0.00,
    "amp_max": 0.25,
    "gamma": 1.6,
    # スムージング
    "alpha_freq": 0.05,
    "alpha_amp": 0.25,
    # マスター音量
    "master_amp": 1.0,
}

PRESET_SCALES = {
    "B Minor Pentatonic":   [4, 11, 1],
    "A Minor Pentatonic":   [9, 0, 2, 5, 7],
    "C Major":              [0, 2, 4, 5, 7, 9, 11],
    "C Major Pentatonic":   [0, 2, 4, 7, 9],
    "D Dorian":             [2, 4, 5, 7, 9, 11, 0],
    "Blues Scale (A)":      [9, 0, 2, 3, 4, 7],
    "Chromatic":            list(range(12)),
    "Custom":               [],
}

SETTINGS_FILE = os.path.join(os.path.dirname(__file__), "theremin_settings.json")
CORE_SCRIPT   = os.path.join(os.path.dirname(__file__), "theremin_sound_v4_0.py")

# ──────────────────────────────────────────────
# カラーパレット（合成器・テルミン風ダークテーマ）
# ──────────────────────────────────────────────
C = {
    "bg":         "#0e0e14",
    "panel":      "#16161f",
    "border":     "#2a2a3a",
    "accent":     "#00e5ff",
    "accent2":    "#ff6b6b",
    "accent3":    "#a8ff78",
    "text":       "#e8e8f0",
    "text_dim":   "#7070a0",
    "entry_bg":   "#1e1e2e",
    "entry_fg":   "#e8e8f0",
    "btn_run":    "#00c896",
    "btn_stop":   "#ff4444",
    "btn_hover":  "#00ffbe",
}

FONT_MONO = ("Courier New", 9)
FONT_UI   = ("Segoe UI", 9) if sys.platform == "win32" else ("Helvetica", 9)
FONT_HEAD = ("Segoe UI", 10, "bold") if sys.platform == "win32" else ("Helvetica", 10, "bold")
FONT_TITLE = ("Courier New", 14, "bold")


# ──────────────────────────────────────────────
# ユーティリティ
# ──────────────────────────────────────────────
def save_settings(cfg: dict):
    with open(SETTINGS_FILE, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2, ensure_ascii=False)


def load_settings() -> dict:
    if os.path.exists(SETTINGS_FILE):
        try:
            with open(SETTINGS_FILE, encoding="utf-8") as f:
                data = json.load(f)
            merged = {**DEFAULTS, **data}
            return merged
        except Exception:
            pass
    return dict(DEFAULTS)


def get_audio_devices():
    """sounddevice で出力デバイス一覧取得（失敗時は空リスト）"""
    try:
        import sounddevice as sd
        devs = sd.query_devices()
        out = []
        for i, d in enumerate(devs):
            if d["max_output_channels"] > 0:
                out.append((i, d["name"]))
        return out
    except Exception:
        return []


# ──────────────────────────────────────────────
# コードジェネレーター
# ──────────────────────────────────────────────
def generate_script(cfg: dict) -> str:
    """設定から実行用Pythonスクリプト文字列を生成する"""

    if cfg["scale_name"] == "Custom":
        try:
            pcs = [int(x.strip()) for x in cfg["custom_pcs"].split(",") if x.strip()]
        except Exception:
            pcs = DEFAULTS["custom_pcs"]
    else:
        pcs = PRESET_SCALES.get(cfg["scale_name"], [4, 11, 1])

    # 強調ルート音（先頭音）
    root_pc = pcs[0] if pcs else 0

    script = f'''# Auto-generated by Theremin GUI
import cv2
import mediapipe as mp
import math
import numpy as np
import os

os.environ["SD_ENABLE_ASIO"] = "1"

import sounddevice as sd

# ── Pitch helpers ──
A4 = 440.0

def midi_from_freq(f):
    return 69 + 12 * math.log2(f / A4)

def freq_from_midi(m):
    return A4 * (2 ** ((m - 69) / 12))

def y_to_freq(y_norm, y_low={cfg["y_low"]}, y_high={cfg["y_high"]}, f_min={cfg["f_min"]}, octaves={cfg["octaves"]}):
    y = min(max(y_norm, y_high), y_low)
    u = (y_low - y) / (y_low - y_high)
    return f_min * (2 ** (u * octaves))

def freq_to_y(freq, y_low={cfg["y_low"]}, y_high={cfg["y_high"]}, f_min={cfg["f_min"]}, octaves={cfg["octaves"]}):
    freq = max(freq, 1e-6)
    u = math.log2(freq / f_min) / octaves
    u = min(max(u, 0.0), 1.0)
    return y_low - (y_low - y_high) * u

# ── Scale ──
SCALE_PCS = {pcs}

NOTE_NAMES = {{
    0:"C",1:"C#",2:"D",3:"D#",4:"E",5:"F",
    6:"F#",7:"G",8:"G#",9:"A",10:"A#",11:"B",
}}

def midi_to_note_name(m):
    m = int(round(m))
    return f"{{NOTE_NAMES[m % 12]}}{{(m // 12) - 1}}"

def build_scale_midis(midi_min, midi_max, pitch_classes):
    out = []
    for m in range(int(math.floor(midi_min)) - 12, int(math.ceil(midi_max)) + 13):
        if (m % 12) in pitch_classes:
            out.append(m)
    return out

def quantize_midi_to_scale(midi_value, scale_midis):
    return min(scale_midis, key=lambda m: abs(m - midi_value))

# ── Volume (pinch) ──
def clamp(x, lo, hi):
    return lo if x < lo else hi if x > hi else x

def pinch_to_amp(pinch_norm,
                 pinch_min={cfg["pinch_min"]}, pinch_max={cfg["pinch_max"]},
                 amp_min={cfg["amp_min"]},   amp_max={cfg["amp_max"]},
                 gamma={cfg["gamma"]}):
    p = clamp(pinch_norm, pinch_min, pinch_max)
    u = (p - pinch_min) / (pinch_max - pinch_min)
    u = u ** gamma
    return amp_min + (amp_max - amp_min) * u

# ── Audio ──
SR      = {int(cfg["samplerate"])}
BLOCK   = {int(cfg["blocksize"])}
DEVICE  = {int(cfg["device_index"])}

state = {{
    "phase": 0.0,
    "freq": 220.0,
    "amp": 0.0,
    "target_freq": 220.0,
    "target_amp": 0.0,
}}

def audio_callback(outdata, frames, time, status):
    if status:
        print("audio status:", status)
    alpha_f = {cfg["alpha_freq"]}
    alpha_a = {cfg["alpha_amp"]}
    state["freq"] = (1 - alpha_f) * state["freq"] + alpha_f * state["target_freq"]
    state["amp"]  = (1 - alpha_a) * state["amp"]  + alpha_a * state["target_amp"]
    indices = np.arange(frames, dtype=np.float32)
    phases  = state["phase"] + 2.0 * np.pi * state["freq"] * indices / SR
    y = (state["amp"] * np.sin(phases)).astype(np.float32)
    state["phase"] = (phases[-1] + 2.0 * np.pi * state["freq"] / SR) % (2.0 * np.pi)
    outdata[:, 0] = y
    outdata[:, 1] = y

# ── MediaPipe ──
mp_hands = mp.solutions.hands
mp_draw  = mp.solutions.drawing_utils

hands = mp_hands.Hands(
    model_complexity=0,
    max_num_hands=2,
    min_detection_confidence=0.45,
    min_tracking_confidence=0.45,
)

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)
if not cap.isOpened():
    raise RuntimeError("Camera not found / cannot open.")

y_low, y_high = {cfg["y_low"]}, {cfg["y_high"]}
f_min, octaves = {cfg["f_min"]}, {cfg["octaves"]}

midi_min = midi_from_freq(f_min)
midi_max = midi_from_freq(f_min * (2 ** octaves))
SCALE_MIDIS = build_scale_midis(midi_min, midi_max, SCALE_PCS)

def draw_guides(frame):
    h, w, _ = frame.shape
    cv2.rectangle(frame, (0, int(y_high * h)), (w - 1, int(y_low * h)), (200, 200, 200), 1)
    for m in SCALE_MIDIS:
        f  = freq_from_midi(m)
        y  = freq_to_y(f)
        yy = int(y * h)
        if (m % 12) == {root_pc}:
            color, thickness = (0, 200, 255), 2
        else:
            color, thickness = (255, 255, 255), 1
        cv2.line(frame, (0, yy), (w, yy), color, thickness)
        cv2.putText(frame, midi_to_note_name(m), (w - 70, yy - 4),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 1)

print("Theremin - Scale: {cfg["scale_name"]} {pcs}")
print("Controls: q=quit, m=mute/unmute, [ ] = volume down/up")

muted     = False
master_amp = {cfg["master_amp"]}

stream = sd.OutputStream(
    device=DEVICE, samplerate=SR, blocksize=BLOCK,
    channels=2, dtype="float32", latency="low",
    callback=audio_callback,
)
stream.start()

try:
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame = cv2.flip(frame, 1)
        rgb   = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        res   = hands.process(rgb)

        draw_guides(frame)

        pitch_found = False
        vol_found   = False
        target_amp_from_left = 0.0

        if res.multi_hand_landmarks:
            for hand_lm in res.multi_hand_landmarks:
                lm = hand_lm.landmark
                mp_draw.draw_landmarks(frame, hand_lm, mp_hands.HAND_CONNECTIONS)
                hand_center_x = lm[0].x

                if hand_center_x > 0.5:
                    idx    = lm[mp_hands.HandLandmark.INDEX_FINGER_TIP]
                    f_cont = y_to_freq(idx.y)
                    m_cont = midi_from_freq(max(f_cont, 1e-6))
                    m_q    = quantize_midi_to_scale(m_cont, SCALE_MIDIS)
                    f_q    = freq_from_midi(m_q)
                    state["target_freq"] = f_q
                    pitch_found = True
                    h2, w2, _ = frame.shape
                    yy = int(idx.y * h2)
                    cv2.line(frame, (0, yy), (w2, yy), (0, 255, 0), 2)
                    cv2.putText(frame,
                        f"RIGHT(pitch): {{midi_to_note_name(m_q)}}  {{f_q:.1f}}Hz",
                        (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)
                else:
                    th    = lm[mp_hands.HandLandmark.THUMB_TIP]
                    idx   = lm[mp_hands.HandLandmark.INDEX_FINGER_TIP]
                    pinch = math.hypot(th.x - idx.x, th.y - idx.y)
                    target_amp_from_left = pinch_to_amp(pinch) * master_amp
                    vol_found = True
                    cv2.putText(frame,
                        f"LEFT(vol): amp={{target_amp_from_left:.2f}}",
                        (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 0), 2)

        if muted:
            state["target_amp"] = 0.0
        else:
            state["target_amp"] = target_amp_from_left if (pitch_found and vol_found) else 0.0

        if not pitch_found:
            cv2.putText(frame, "RIGHT: no hand (pitch)",
                (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)
        if not vol_found:
            cv2.putText(frame, "LEFT: no hand (volume)",
                (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 255), 2)

        cv2.imshow("Theremin - {cfg["scale_name"]}", frame)
        key = cv2.waitKey(1) & 0xFF

        if key == ord("q"):
            break
        elif key == ord("m"):
            muted = not muted
        elif key == ord("["):
            master_amp = max(0.0, master_amp - 0.05)
        elif key == ord("]"):
            master_amp = min(2.0, master_amp + 0.05)

finally:
    stream.stop()
    stream.close()
    cap.release()
    cv2.destroyAllWindows()
    hands.close()
'''
    return script


# ──────────────────────────────────────────────
# メインGUIクラス
# ──────────────────────────────────────────────
class ThereminGUI:
    def __init__(self, root: tk.Tk):
        self.root = root
        self.root.title("🎵 Theremin GUI")
        self.root.configure(bg=C["bg"])
        self.root.resizable(True, True)
        self.root.minsize(700, 620)

        self.cfg = load_settings()
        self.process: subprocess.Popen | None = None
        self._vars: dict = {}
        self._log_lines = 0

        self._build_ui()
        self._apply_cfg_to_vars()
        self._refresh_device_list()
        self.root.protocol("WM_DELETE_WINDOW", self._on_close)

    # ── UI構築 ──────────────────────────────
    def _build_ui(self):
        # ヘッダー
        hdr = tk.Frame(self.root, bg=C["bg"])
        hdr.pack(fill="x", padx=20, pady=(16, 8))

        tk.Label(hdr, text="◈ THEREMIN", font=FONT_TITLE,
                 fg=C["accent"], bg=C["bg"]).pack(side="left")
        tk.Label(hdr, text=" CONTROL PANEL", font=FONT_TITLE,
                 fg=C["text_dim"], bg=C["bg"]).pack(side="left")

        self.status_dot = tk.Label(hdr, text="●", font=("Courier New", 18),
                                   fg=C["text_dim"], bg=C["bg"])
        self.status_dot.pack(side="right", padx=(0, 4))
        self.status_lbl = tk.Label(hdr, text="STOPPED", font=FONT_MONO,
                                   fg=C["text_dim"], bg=C["bg"])
        self.status_lbl.pack(side="right")

        sep = tk.Frame(self.root, bg=C["border"], height=1)
        sep.pack(fill="x", padx=20, pady=0)

        # ─ メインエリア（左パネル + ログ）─
        body = tk.Frame(self.root, bg=C["bg"])
        body.pack(fill="both", expand=True, padx=20, pady=12)

        left = tk.Frame(body, bg=C["bg"])
        left.pack(side="left", fill="both", expand=True)

        right = tk.Frame(body, bg=C["bg"], width=220)
        right.pack(side="right", fill="y", padx=(12, 0))
        right.pack_propagate(False)

        # ── 左：設定セクション ──
        self._build_scale_section(left)
        self._build_range_section(left)
        self._build_audio_section(left)
        self._build_sensitivity_section(left)
        self._build_smoothing_section(left)

        # ── 右：ログ + ボタン ──
        self._build_log_panel(right)
        self._build_buttons(right)

    def _section(self, parent, title):
        frame = tk.Frame(parent, bg=C["panel"],
                         highlightbackground=C["border"],
                         highlightthickness=1)
        frame.pack(fill="x", pady=(0, 8))
        tk.Label(frame, text=f"  {title}", font=FONT_HEAD,
                 fg=C["accent"], bg=C["panel"],
                 anchor="w").pack(fill="x", ipady=4)
        tk.Frame(frame, bg=C["border"], height=1).pack(fill="x")
        inner = tk.Frame(frame, bg=C["panel"])
        inner.pack(fill="x", padx=10, pady=8)
        return inner

    def _row(self, parent, label, widget_factory, col_weight=1):
        row = tk.Frame(parent, bg=C["panel"])
        row.pack(fill="x", pady=2)
        tk.Label(row, text=label, font=FONT_UI, fg=C["text_dim"],
                 bg=C["panel"], width=20, anchor="w").pack(side="left")
        w = widget_factory(row)
        w.pack(side="left", fill="x", expand=True)
        return w

    def _entry(self, parent, key, width=12, fmt=None):
        var = tk.StringVar()
        self._vars[key] = var
        e = tk.Entry(parent, textvariable=var, width=width,
                     bg=C["entry_bg"], fg=C["entry_fg"],
                     insertbackground=C["accent"],
                     relief="flat", font=FONT_MONO,
                     highlightbackground=C["border"],
                     highlightthickness=1)
        return e

    def _slider(self, parent, key, from_, to, resolution=0.01, digits=3):
        var = tk.DoubleVar()
        self._vars[key] = var
        s = tk.Scale(parent, variable=var, from_=from_, to=to,
                     resolution=resolution, orient="horizontal",
                     bg=C["panel"], fg=C["text"], troughcolor=C["border"],
                     activebackground=C["accent"], highlightthickness=0,
                     sliderrelief="flat", digits=digits,
                     font=FONT_MONO, length=180)
        return s

    def _combo(self, parent, key, values):
        var = tk.StringVar()
        self._vars[key] = var
        cb = ttk.Combobox(parent, textvariable=var, values=values,
                          state="readonly", font=FONT_MONO)
        cb.configure()
        return cb

    # ── セクション別 ────────────────────────
    def _build_scale_section(self, parent):
        sec = self._section(parent, "♩ SCALE")

        self._row(sec, "Preset Scale",
                  lambda p: self._combo(p, "scale_name",
                                        list(PRESET_SCALES.keys())))

        cpc_row = tk.Frame(sec, bg=C["panel"])
        cpc_row.pack(fill="x", pady=2)
        tk.Label(cpc_row, text="Custom Pitch Classes",
                 font=FONT_UI, fg=C["text_dim"], bg=C["panel"],
                 width=20, anchor="w").pack(side="left")
        e = self._entry(cpc_row, "custom_pcs", width=24)
        e.pack(side="left")
        tk.Label(cpc_row, text=" (e.g. 0,2,4,7,9)", font=FONT_MONO,
                 fg=C["text_dim"], bg=C["panel"]).pack(side="left")

        # スケール変更時にカスタムフィールドの有効/無効を切り替え
        def on_scale_change(*_):
            name = self._vars["scale_name"].get()
            state = "normal" if name == "Custom" else "disabled"
            e.config(state=state)
        self._vars["scale_name"].trace_add("write", on_scale_change)

    def _build_range_section(self, parent):
        sec = self._section(parent, "↕ PITCH RANGE")
        self._row(sec, "Min Freq (Hz)",
                  lambda p: self._slider(p, "f_min", 55, 440, resolution=1, digits=4))
        self._row(sec, "Octaves",
                  lambda p: self._slider(p, "octaves", 1.0, 5.0, resolution=0.5, digits=2))
        self._row(sec, "Y Low (0~1)",
                  lambda p: self._slider(p, "y_low", 0.5, 1.0, resolution=0.01))
        self._row(sec, "Y High (0~1)",
                  lambda p: self._slider(p, "y_high", 0.0, 0.5, resolution=0.01))

    def _build_audio_section(self, parent):
        sec = self._section(parent, "🔊 AUDIO DRIVER")

        dev_row = tk.Frame(sec, bg=C["panel"])
        dev_row.pack(fill="x", pady=2)
        tk.Label(dev_row, text="Output Device", font=FONT_UI,
                 fg=C["text_dim"], bg=C["panel"], width=20, anchor="w").pack(side="left")

        self._vars["device_index"] = tk.IntVar(value=self.cfg["device_index"])
        self.device_combo_var = tk.StringVar()
        self.device_combo = ttk.Combobox(dev_row, textvariable=self.device_combo_var,
                                          state="readonly", font=FONT_MONO, width=30)
        self.device_combo.pack(side="left", fill="x", expand=True)

        tk.Button(dev_row, text="⟳", font=FONT_MONO,
                  bg=C["border"], fg=C["accent"],
                  relief="flat", cursor="hand2",
                  command=self._refresh_device_list).pack(side="left", padx=(4, 0))

        self._row(sec, "Sample Rate (Hz)",
                  lambda p: self._combo(p, "samplerate",
                                        ["44100", "48000", "96000"]))
        self._row(sec, "Block Size",
                  lambda p: self._combo(p, "blocksize",
                                        ["128", "256", "512", "1024"]))

    def _build_sensitivity_section(self, parent):
        sec = self._section(parent, "🤏 PINCH SENSITIVITY")
        self._row(sec, "Pinch Min",
                  lambda p: self._slider(p, "pinch_min", 0.0, 0.15, resolution=0.005))
        self._row(sec, "Pinch Max",
                  lambda p: self._slider(p, "pinch_max", 0.10, 0.50, resolution=0.005))
        self._row(sec, "Amp Max",
                  lambda p: self._slider(p, "amp_max", 0.0, 1.0, resolution=0.01))
        self._row(sec, "Gamma",
                  lambda p: self._slider(p, "gamma", 0.5, 4.0, resolution=0.1, digits=2))
        self._row(sec, "Master Volume",
                  lambda p: self._slider(p, "master_amp", 0.0, 2.0, resolution=0.05))

    def _build_smoothing_section(self, parent):
        sec = self._section(parent, "〜 SMOOTHING")
        self._row(sec, "Freq Smooth α",
                  lambda p: self._slider(p, "alpha_freq", 0.01, 0.5, resolution=0.01))
        self._row(sec, "Amp Smooth α",
                  lambda p: self._slider(p, "alpha_amp", 0.01, 1.0, resolution=0.01))

    def _build_log_panel(self, parent):
        tk.Label(parent, text="LOG", font=FONT_HEAD,
                 fg=C["text_dim"], bg=C["bg"]).pack(anchor="w", pady=(0, 4))
        self.log_box = scrolledtext.ScrolledText(
            parent, font=FONT_MONO, bg=C["entry_bg"], fg=C["text"],
            insertbackground=C["accent"], relief="flat",
            state="disabled", wrap="word",
            highlightbackground=C["border"], highlightthickness=1)
        self.log_box.pack(fill="both", expand=True)

    def _build_buttons(self, parent):
        btn_frame = tk.Frame(parent, bg=C["bg"])
        btn_frame.pack(fill="x", pady=(10, 0))

        self.run_btn = tk.Button(
            btn_frame, text="▶  RUN", font=("Courier New", 11, "bold"),
            bg=C["btn_run"], fg="#000", activebackground=C["btn_hover"],
            relief="flat", cursor="hand2", height=2,
            command=self._run)
        self.run_btn.pack(fill="x", pady=(0, 6))

        self.stop_btn = tk.Button(
            btn_frame, text="■  STOP", font=("Courier New", 11, "bold"),
            bg=C["btn_stop"], fg="#fff", activebackground="#ff8888",
            relief="flat", cursor="hand2", height=2,
            state="disabled", command=self._stop)
        self.stop_btn.pack(fill="x", pady=(0, 6))

        tk.Button(btn_frame, text="💾 Save Settings", font=FONT_UI,
                  bg=C["border"], fg=C["text"], relief="flat",
                  cursor="hand2", command=self._save).pack(fill="x", pady=(0, 4))

        tk.Button(btn_frame, text="↺ Reset Defaults", font=FONT_UI,
                  bg=C["border"], fg=C["text_dim"], relief="flat",
                  cursor="hand2", command=self._reset).pack(fill="x")

    # ── 値の適用 / 収集 ──────────────────────
    def _apply_cfg_to_vars(self):
        for key, var in self._vars.items():
            val = self.cfg.get(key)
            if val is None:
                continue
            try:
                if isinstance(var, tk.StringVar):
                    var.set(str(val))
                elif isinstance(var, (tk.DoubleVar, tk.IntVar)):
                    var.set(val)
            except Exception:
                pass

    def _collect_cfg(self) -> dict:
        cfg = dict(self.cfg)
        for key, var in self._vars.items():
            try:
                raw = var.get()
                if key in ("samplerate", "blocksize"):
                    cfg[key] = int(raw)
                elif key in ("scale_name", "custom_pcs"):
                    cfg[key] = raw
                elif isinstance(var, tk.IntVar):
                    cfg[key] = int(raw)
                else:
                    cfg[key] = float(raw)
            except Exception:
                pass
        # デバイスインデックスをコンボから取得
        sel = self.device_combo.current()
        if sel >= 0 and sel < len(self._device_list):
            cfg["device_index"] = self._device_list[sel][0]
        return cfg

    # ── デバイスリスト更新 ────────────────────
    def _refresh_device_list(self):
        devs = get_audio_devices()
        self._device_list = devs
        labels = [f"[{i}] {name}" for i, name in devs]
        self.device_combo["values"] = labels if labels else ["(no output devices found)"]

        # 設定値と一致するデバイスを選択
        target = self.cfg.get("device_index", 8)
        for idx, (dev_i, _) in enumerate(devs):
            if dev_i == target:
                self.device_combo.current(idx)
                return
        if labels:
            self.device_combo.current(0)

    # ── 実行 / 停止 ──────────────────────────
    def _run(self):
        if self.process and self.process.poll() is None:
            messagebox.showinfo("Running", "Already running.")
            return

        cfg = self._collect_cfg()
        script_code = generate_script(cfg)

        # 一時スクリプトに書き出し
        tmp_path = os.path.join(os.path.dirname(__file__), "_theremin_run.py")
        with open(tmp_path, "w", encoding="utf-8") as f:
            f.write(script_code)

        self._log(f"▶ Starting theremin (scale={cfg['scale_name']}, "
                  f"device={cfg['device_index']}, sr={cfg['samplerate']})\n")

        try:
            self.process = subprocess.Popen(
                [sys.executable, tmp_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
        except Exception as e:
            self._log(f"[ERROR] {e}\n")
            return

        self._set_running(True)
        threading.Thread(target=self._read_output, daemon=True).start()

    def _stop(self):
        if self.process:
            try:
                self.process.terminate()
            except Exception:
                pass
        self._set_running(False)
        self._log("■ Stopped.\n")

    def _read_output(self):
        try:
            for line in self.process.stdout:
                self._log(line)
        except Exception:
            pass
        self.process.wait()
        rc = self.process.returncode
        self._log(f"[Process exited: {rc}]\n")
        self.root.after(0, lambda: self._set_running(False))

    def _set_running(self, running: bool):
        if running:
            self.run_btn.config(state="disabled")
            self.stop_btn.config(state="normal")
            self.status_dot.config(fg=C["accent3"])
            self.status_lbl.config(text="RUNNING", fg=C["accent3"])
        else:
            self.run_btn.config(state="normal")
            self.stop_btn.config(state="disabled")
            self.status_dot.config(fg=C["text_dim"])
            self.status_lbl.config(text="STOPPED", fg=C["text_dim"])

    # ── ログ ──────────────────────────────────
    def _log(self, text: str):
        def _inner():
            self.log_box.config(state="normal")
            self.log_box.insert("end", text)
            self.log_box.see("end")
            self._log_lines += text.count("\n")
            if self._log_lines > 500:
                self.log_box.delete("1.0", "200.0")
                self._log_lines -= 200
            self.log_box.config(state="disabled")
        self.root.after(0, _inner)

    # ── 保存 / リセット ──────────────────────
    def _save(self):
        cfg = self._collect_cfg()
        save_settings(cfg)
        self.cfg = cfg
        self._log("💾 Settings saved.\n")

    def _reset(self):
        if messagebox.askyesno("Reset", "Restore all defaults?"):
            self.cfg = dict(DEFAULTS)
            self._apply_cfg_to_vars()
            self._refresh_device_list()
            self._log("↺ Reset to defaults.\n")

    def _on_close(self):
        self._stop()
        self.root.destroy()


# ──────────────────────────────────────────────
# エントリーポイント
# ──────────────────────────────────────────────
def main():
    # ttk スタイル設定
    root = tk.Tk()

    style = ttk.Style(root)
    # ダークなコンボボックス
    style.theme_use("clam")
    style.configure("TCombobox",
                    fieldbackground=C["entry_bg"],
                    background=C["entry_bg"],
                    foreground=C["entry_fg"],
                    arrowcolor=C["accent"],
                    bordercolor=C["border"],
                    darkcolor=C["border"],
                    lightcolor=C["border"])
    style.map("TCombobox",
              fieldbackground=[("readonly", C["entry_bg"])],
              foreground=[("readonly", C["entry_fg"])],
              selectbackground=[("readonly", C["border"])])

    app = ThereminGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()
